-- V1__baseline.sql
-- Baseline schema for KeyBudget — all tables derived from JPA entities

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_sub  VARCHAR(255) NOT NULL UNIQUE,
    email       VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    picture_url VARCHAR(255),
    created_at  TIMESTAMP NOT NULL
);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti        VARCHAR(255) NOT NULL UNIQUE,
    user_id    BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    family_id  VARCHAR(255) NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    icon       VARCHAR(255),
    color      VARCHAR(255),
    type       VARCHAR(255) NOT NULL,
    user_id    BIGINT,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE transactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    amount      NUMERIC(12, 2) NOT NULL,
    description VARCHAR(255),
    date        DATE NOT NULL,
    type        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP NOT NULL
);

CREATE TABLE budgets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    month_year  VARCHAR(7) NOT NULL,
    limit_amount NUMERIC(12, 2) NOT NULL,
    version     BIGINT,
    created_at  TIMESTAMP NOT NULL,
    CONSTRAINT uk_budget_user_category_month UNIQUE (user_id, category_id, month_year)
);

CREATE TABLE integration_credentials (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    provider_type   VARCHAR(50) NOT NULL,
    credential_data TEXT NOT NULL,
    status          VARCHAR(20) NOT NULL,
    last_synced_at  TIMESTAMP,
    error_message   VARCHAR(500),
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    CONSTRAINT uq_integration_credential_user_provider UNIQUE (user_id, provider_type),
    CONSTRAINT fk_integration_credential_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE financial_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    credential_id BIGINT NOT NULL,
    provider_type VARCHAR(50) NOT NULL,
    account_type  VARCHAR(30) NOT NULL,
    external_id   VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    currency      VARCHAR(10) NOT NULL,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL,
    CONSTRAINT uq_financial_account_credential_external_id UNIQUE (credential_id, external_id),
    CONSTRAINT fk_financial_account_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_financial_account_credential FOREIGN KEY (credential_id) REFERENCES integration_credentials (id)
);

CREATE TABLE financial_account_balances (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT NOT NULL UNIQUE,
    balance     NUMERIC(18, 8) NOT NULL,
    balance_usd NUMERIC(14, 2) NOT NULL,
    as_of       TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    CONSTRAINT fk_account_balance_account FOREIGN KEY (account_id) REFERENCES financial_accounts (id)
);

CREATE TABLE balance_snapshots (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT NOT NULL,
    balance     NUMERIC(18, 8) NOT NULL,
    balance_usd NUMERIC(14, 2) NOT NULL,
    recorded_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_balance_snapshot_account FOREIGN KEY (account_id) REFERENCES financial_accounts (id)
);

CREATE INDEX idx_balance_snapshot_account_recorded_at ON balance_snapshots (account_id, recorded_at DESC);
